services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: aiap-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - UVICORN_RELOAD=true
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-dev-secret-THIS-IS-DEV-ONLY-12345678901234567890}
      - CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,http://frontend:3000
    volumes:
      - ./:/app
      - backend_venv_cache:/root/.cache/pip
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - node-red

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: aiap-frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - BROWSER=none
      - API_PROXY_TARGET=http://backend:8000
    volumes:
      - ./frontend:/usr/src/app
      - frontend_node_modules:/usr/src/app/node_modules
    depends_on:
      - backend

  node-red:
    build:
      context: .
      dockerfile: Dockerfile.nodered
    container_name: aiap-nodered
    ports:
      - "1880:1880"
    environment:
      - NODE_ENV=development
    volumes:
      - ./node-red:/usr/src/node-red
      - node_red_data:/usr/src/node-red/node-red-data

volumes:
  backend_venv_cache:
  frontend_node_modules:
  node_red_data:
