services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: aiap-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - UVICORN_RELOAD=true
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    volumes:
      - ./:/app
      - backend_venv_cache:/root/.cache/pip
      - backend_db:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - node-red

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: aiap-frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - BROWSER=none
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend

  node-red:
    build:
      context: .
      dockerfile: node-red/Dockerfile
    container_name: aiap-nodered
    ports:
      - "1880:1880"
    environment:
      - NODE_ENV=development
    volumes:
      - ./node-red:/usr/src/node-red
      - node_red_data:/usr/src/node-red/node-red-data

volumes:
  backend_db:
  backend_venv_cache:
  node_red_data:
